# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "8cb3d828c75ef9d789b768c6c0222db9"
name = "product-reviews-app"
handle = "product-reviews-app-13"
application_url = "https://doubt-tampa-gpl-professor.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "xuthi.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,write_products"

[auth]
redirect_urls = [
  "https://doubt-tampa-gpl-professor.trycloudflare.com/auth/callback",
  "https://doubt-tampa-gpl-professor.trycloudflare.com/auth/shopify/callback",
  "https://doubt-tampa-gpl-professor.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/data_request"
  compliance_topics = [ "customers/data_request" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/redact"
  compliance_topics = [ "customers/redact" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/shop/redact"
  compliance_topics = [ "shop/redact" ]

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[app_proxy]
url = "https://doubt-tampa-gpl-professor.trycloudflare.com/api/reviews"
subpath = "product-rating"
prefix = "apps"

[pos]
embedded = false
